spring.application.name=bookshop01_boot

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

server.servlet.context-path=/
server.port=8080

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
# 기존 설정
# spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe

# 서버 DB 설정
spring.datasource.url=jdbc:oracle:thin:@//34.22.64.240:1521/xe
spring.datasource.username=system
spring.datasource.password=1234

mybatis.mapper-locations=classpath:/mybatis/mappers/*.xml
mybatis.type-aliases-package=com.bookshop01

mybatis.configuration.map-underscore-to-camel-case=true